debezium.sink.type=rabbitmq

debezium.sink.rabbitmq.connection.host=${RABBITMQ_HOST}
debezium.sink.rabbitmq.connection.port=5672
debezium.sink.rabbitmq.connection.username=${RABBITMQ_USERNAME}
debezium.sink.rabbitmq.connection.password=${RABBITMQ_PASSWORD}
debezium.sink.rabbitmq.exchange=${RABBITMQ_EXCHANGE}
debezium.sink.rabbitmq.routingKey=${RABBITMQ_ROUTINGKEY}

debezium.source.connector.class=io.debezium.connector.mysql.MySqlConnector
debezium.source.database.hostname=${DB_HOST}
debezium.source.database.port=3306
debezium.source.database.user=${DB_USERNAME}
debezium.source.database.password=${DB_PASSWORD}
debezium.source.database.connectionTimeZone=Asia/Seoul
debezium.source.database.server.id=15551
debezium.source.topic.prefix=cdc.event
debezium.source.database.include.list=api
debezium.source.table.include.list=api.outbox_event

debezium.source.key.converter=org.apache.kafka.connect.json.JsonConverter
debezium.source.key.converter.schemas.enable=false
debezium.source.value.converter=org.apache.kafka.connect.json.JsonConverter
debezium.source.value.converter.schemas.enable=false

debezium.source.offset.storage.file.filename=data/offsets.dat
debezium.source.offset.flush.interval.ms=10000
debezium.source.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory
debezium.source.schema.history.internal.file.filename=data/schemahistory.dat
