debezium.sink.type=rabbitmq

debezium.sink.rabbitmq.connection.host=${DEBEZIUM_RABBITMQ_HOST}
debezium.sink.rabbitmq.connection.port=${DEBEZIUM_RABBITMQ_PORT}
debezium.sink.rabbitmq.connection.username=${DEBEZIUM_RABBITMQ_USERNAME}
debezium.sink.rabbitmq.connection.password=${DEBEZIUM_RABBITMQ_PASSWORD}

debezium.sink.rabbitmq.exchange=cdc.event.exchange
debezium.sink.rabbitmq.routingKey=cdc.event.message

debezium.source.connector.class=io.debezium.connector.mysql.MySqlConnector

debezium.source.database.hostname=${DEBEZIUM_DB_HOST}
debezium.source.database.port=${DEBEZIUM_DB_PORT}
debezium.source.database.user=${DEBEZIUM_DB_USERNAME}
debezium.source.database.password=${DEBEZIUM_DB_PASSWORD}
debezium.source.database.connectionTimeZone=Asia/Seoul

debezium.source.database.server.id=${DEBEZIUM_DB_SERVER_ID}
debezium.source.topic.prefix=cdc.event

debezium.source.database.include.list=api
debezium.source.table.include.list=api.outbox_event

debezium.source.key.converter=org.apache.kafka.connect.json.JsonConverter
debezium.source.key.converter.schemas.enable=false
debezium.source.value.converter=org.apache.kafka.connect.json.JsonConverter
debezium.source.value.converter.schemas.enable=false

# ?? ??? ?? (??? ? ??? ?? ?? ??)
# ??? ??
debezium.source.offset.storage.file.filename=data/offsets.dat
debezium.source.offset.flush.interval.ms=10000

# ??? ?? ??
debezium.source.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory
debezium.source.schema.history.internal.file.filename=data/schemahistory.dat
