# sink(???) ??
debezium.sink.type=rabbitmq
# ???? rabbitMQ ??
# ??? ???
debezium.sink.rabbitmq.connection.host=host.docker.internal
debezium.sink.rabbitmq.connection.port=5672
# rmq ?? ??
debezium.sink.rabbitmq.connection.username=admin
debezium.sink.rabbitmq.connection.password=admin
# debezium? ?? ?? ???? RabbitMQConfig? ??? exchange & routing key ? ?
debezium.sink.rabbitmq.exchange=cdc.event.exchange
# ????? -> 3.4 ????? routingKey ? ?????? ????
debezium.sink.rabbitmq.routingKey=cdc.event.message

# source ??(???? ??? ??? MySQL)
debezium.source.connector.class=io.debezium.connector.mysql.MySqlConnector

# MySQL ?? ??(??? ??)
debezium.source.database.hostname=file-conversion-database-1.cn6kiey0qu1a.ap-northeast-2.rds.amazonaws.com
debezium.source.database.port=3306
debezium.source.database.user=toyboyz
debezium.source.database.password=toytoy123
debezium.source.database.connectionTimeZone=Asia/Seoul

# db ?? ???????? ?? id/ ?? slave OR debezium? ??? ??
debezium.source.database.server.id=54321
# ??? ? ??
debezium.source.topic.prefix=cdc.event
# ??? ?????? ??? ?? ???? ??
debezium.source.database.include.list=api
debezium.source.table.include.list=api.outbox_event

# ??? ?? ?? (json)
debezium.source.key.converter=org.apache.kafka.connect.json.JsonConverter
debezium.source.key.converter.schemas.enable=false
debezium.source.value.converter=org.apache.kafka.connect.json.JsonConverter
debezium.source.value.converter.schemas.enable=false

# ?? ??? ?? (??? ? ??? ?? ?? ??)
# ??? ??
debezium.source.offset.storage.file.filename=data/offsets.dat
debezium.source.offset.flush.interval.ms=10000

# ??? ?? ??
debezium.source.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory
debezium.source.schema.history.internal.file.filename=data/schemahistory.dat