server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 120s
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      database: ${SPRING_DATA_REDIS_DATABASE}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    rabbit:
      enabled: true

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}

s3:
  bucket: toyboyz-fileconv-bucket
  region: ap-northeast-2
  prefix: uploads
  presign-ttl-seconds: 900
