plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':common-core')
    implementation project(':infra-s3')
    implementation project(':infra-redis')


    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-amqp'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.retry:spring-retry'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-prometheus'

    // 관리자가 해당 로그를 수집하는 경우? 슬랙에서 오는 이벤트를 받는 기능
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    implementation 'com.itextpdf:itext7-core:7.2.5'
    // PDF 핸들링
    implementation 'org.apache.pdfbox:pdfbox:2.0.27'
    // Word (.docx) -> PDF
    implementation 'org.docx4j:docx4j-export-fo:11.4.9'
    implementation 'org.docx4j:docx4j-JAXB-ReferenceImpl:11.4.9'
    implementation 'org.docx4j:docx4j-export-fo:11.4.9'
    // Excel (.xlsx) 핸들링
    implementation 'org.apache.poi:poi-ooxml:5.2.3'

    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.named('jar') {
    enabled = false
}