name: deploy

on:
  push:
    branches: ["develop"]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-2
  AWS_ACCOUNT_ID: "188615717003"
  ECR_REPO: "my-app"
  EC2_INSTANCE_ID: "i-04d273add12b3752e"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - name: Configure AWS credentials (OIDC)
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::188615717003:role/Role-GitHubActions-Deploy
            aws-region: ${{ env.AWS_REGION }}

        - name: Login to Amazon ECR
          uses: aws-actions/amazon-ecr-login@v2

        - name: Build & Push Docker image (date + run number tag)
          id: build
          run: |
            set -euo pipefail

            TAG="$(TZ=Asia/Seoul date +%Y%m%d-%H%M)-${GITHUB_RUN_NUMBER}"
            echo "tag=$TAG" >> "$GITHUB_OUTPUT"
            
            ECR_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}"
            echo "ECR_URI=$ECR_URI"
            echo "TAG=$TAG"
            
            docker build -t "${ECR_URI}:${TAG}" .
            docker push "${ECR_URI}:${TAG}"

        - name: Deploy on EC2 via SSM Run Command
          run: |
            set -euo pipefail
          
            TAG="${{ steps.build.outputs.tag }}"
            echo "Deploy tag: $TAG"
            
            CMD_ID=$(aws ssm send-command \
              --region "${AWS_REGION}" \
              --document-name "AWS-RunShellScript" \
              --instance-ids "${EC2_INSTANCE_ID}" \
              --parameters "{\"commands\":[\"sudo -u ssm-user -H /home/ssm-user/deploy/deploy.sh ${TAG}\"]}" \
              --query "Command.CommandId" \
              --output text)
            
            echo "SSM CommandId: $CMD_ID"
            
            aws ssm wait command-executed \
              --region "${AWS_REGION}" \
              --command-id "$CMD_ID" \
              --instance-id "${EC2_INSTANCE_ID}"
            
            aws ssm get-command-invocation \
              --region "${AWS_REGION}" \
              --command-id "$CMD_ID" \
              --instance-id "${EC2_INSTANCE_ID}" \
              --query "{Status:Status,StdOut:StandardOutputContent,StdErr:StandardErrorContent}"
