name: redis-integration

on:
  pull_request:
    branches: ["dev/v2"]
    paths:
      - "src/main/java/com/toyboyz/fileconversion/infra/redis/**"
      - "src/redisIntegrationTest/**"
      - "build.gradle"
      - "gradle/**"
      - "gradlew"
      - ".github/workflows/redis-integration.yml"
  workflow_dispatch: # 필요하면 수동실행도 가능


jobs:
  redis-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Run Redis integration tests
        run: ./gradlew clean redisIntegrationTest